export default function TermsPage() {
  return (
    <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
      <h1 className="text-3xl font-semibold tracking-tight mb-2">NetCost.ai — Terms of Service</h1>
      <p className="text-sm text-muted mb-10">Effective Date: August 3, 2026</p>

      <p className="text-muted mb-8">
        Welcome to NetCost.ai. These Terms of Service ("Terms") govern your access to and use of
        the NetCost.ai website, application, and wholesale AI gateway services (collectively, the
        "Service"). By accessing or using the Service, you agree to be bound by these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">1. Description of the Service</h2>
      <p className="text-muted mb-6">
        NetCost.ai is a wholesale routing and proxy gateway that allows organizations to connect
        their own third-party artificial intelligence provider credentials (such as API keys from
        OpenAI, Anthropic, or Google) to streamline access and optimize pricing ("BYOK Mode").
        NetCost.ai acts strictly as an infrastructure conduit and technical intermediary between
        your systems and your chosen upstream AI providers.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">2. User Responsibilities &amp; API Key Security</h2>
      <ul className="list-disc list-outside pl-5 text-muted space-y-3 mb-6">
        <li>
          <span className="text-foreground font-medium">Direct Provider Relationship:</span> When
          you use BYOK Mode, you maintain a direct contractual and billing relationship with your
          third-party AI model providers (e.g., OpenAI, Anthropic, Google). NetCost.ai does not
          manage, monitor, or control your direct billing or account status with those third-party
          providers.
        </li>
        <li>
          <span className="text-foreground font-medium">Key Management &amp; Security:</span> You
          are solely responsible for safeguarding your own API credentials, ensuring appropriate
          permissions, and for all activity conducted under your account keys. You agree to rotate
          or revoke your API keys immediately if you suspect any unauthorized access.
        </li>
        <li>
          <span className="text-foreground font-medium">Compliance with Upstream Terms:</span> You
          agree that your use of underlying AI models via our gateway complies with the acceptable
          use policies and terms of service of the respective AI providers (OpenAI, Anthropic,
          Google, etc.).
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-10 mb-3">3. Acceptable Use Policy</h2>
      <p className="text-muted mb-3">You agree not to use NetCost.ai to:</p>
      <ul className="list-disc list-outside pl-5 text-muted space-y-2 mb-6">
        <li>Violate any applicable local, national, or international laws or regulations.</li>
        <li>
          Generate malicious content, distribute malware, conduct cyberattacks, or engage in
          fraudulent activities.
        </li>
        <li>
          Attempt to bypass rate limits, probe, scan, or breach the security infrastructure of the
          Service.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-10 mb-3">4. Limitation of Liability &amp; "As-Is" Disclaimer</h2>
      <ul className="list-disc list-outside pl-5 text-muted space-y-3 mb-6">
        <li>
          <span className="text-foreground font-medium">"As-Is" Basis:</span> The Service is
          provided on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, either
          express or implied. We do not guarantee uninterrupted uptime, error-free routing, or
          absolute compatibility with third-party updates.
        </li>
        <li>
          <span className="text-foreground font-medium">Model Accuracy &amp; Output:</span> AI
          models are prone to hallucinations, errors, and unpredictable outputs. NetCost.ai is not
          responsible for the accuracy, safety, or legal compliance of any content generated by
          underlying third-party LLMs.
        </li>
        <li>
          <span className="text-foreground font-medium">Cap on Liability:</span> To the maximum
          extent permitted by applicable law, NetCost.ai and its operators shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages, or any loss of
          profits or data. Our total aggregate liability for any claims relating to the Service
          shall not exceed the total fees paid by you to NetCost.ai in the three (3) months
          immediately preceding the event giving rise to the claim.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-10 mb-3">5. Suspension and Termination</h2>
      <p className="text-muted mb-6">
        We reserve the right to suspend, restrict, or terminate your access to the Service
        immediately, without prior notice, if we detect fraudulent activity, abusive usage
        patterns, violations of these Terms, or actions that threaten the stability of the
        platform.
      </p>
    </section>
  );
}
